In [19]:
import numpy as np 

In [20]:
## q1
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
##q2
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
##q3
b=a.reshape((3,5))
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
##q4
a.shape

(15,)

In [24]:
##q5
a.ndim

1

In [25]:
##q6
a.size

15

In [26]:
##q7
a.dtype

dtype('int64')

In [27]:
##q8
a.astype(np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.], dtype=float32)

In [28]:
##q9
ones=np.ones((3,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
## q10
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
##q11
a.max()

14

In [31]:
##q12
a.min()

0

In [32]:
### q13
b.sum(axis=1)

array([10, 35, 60])

In [33]:
## q14
b.sum()

105

In [62]:
### q15 How can we split an array into multiple sub-arrays?
# A. Using np.split

'''
numpy.split(ary, indices_or_sections, axis=0)[source]

Split an array into multiple sub-arrays as views into ary.

Parameters:

    aryndarray

        Array to be divided into sub-arrays.
    indices_or_sectionsint or 1-D array

        If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

        If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in

                ary[:2]

                ary[2:3]

                ary[3:]


'''


a15=np.arange(8)

a15=a15.reshape((4,2))
print(np.split(a15,2,axis=0))

[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]])]


In [35]:
### q16 How can we concatenate multiple arrays?
c=np.arange(24)
d=np.arange(48)
e=np.arange(12)
c1=c.reshape((4,-1))
c2=d.reshape((4,-1))
c3=e.reshape((4,-1))
np.concatenate((c1,c2,c3),axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11,  0,  1,  2],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23,  3,  4,  5],
       [12, 13, 14, 15, 16, 17, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35,  6,  7,  8],
       [18, 19, 20, 21, 22, 23, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47,  9, 10, 11]])

In [52]:
### q17 How can we stack arrays vertically or horizontally?


a = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([[7,8,9],[10,11,12]])
## vertical stacking of 2 d arrays along the newly created 3rd axis

print('vertical stack:- \n',np.stack((a,b),axis=0))

### horizontal stacking of 2d arrays along the column axis

print('horizontal stack:- \n',np.stack((a,b),axis=2))



vertical stack:- 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
horizontal stack:- 
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [58]:
### q18. How can we extract specific elements or sub-arrays from an array?
## A. use selection brackets
a18=np.arange(4*5*8*9)
a18=a18.reshape((4,5,8,9))
# print(a18)

### select the element at the some random index :-
print(a18[1,4,7,8])

### subarray formed by 1st and 9nth column and 3rd row 
## of the 2d matrices of index 1 to 3 in the 0 index 3d matrix 
## contained in the outer most 4d matrix is given by:-

print(a18[0,1:3,2,[0,8]])

719
[[ 90 162]
 [ 98 170]]


In [60]:
### q19 How can we create a copy of an array?
a19=a18.copy()
print(a19)

[[[[   0    1    2 ...    6    7    8]
   [   9   10   11 ...   15   16   17]
   [  18   19   20 ...   24   25   26]
   ...
   [  45   46   47 ...   51   52   53]
   [  54   55   56 ...   60   61   62]
   [  63   64   65 ...   69   70   71]]

  [[  72   73   74 ...   78   79   80]
   [  81   82   83 ...   87   88   89]
   [  90   91   92 ...   96   97   98]
   ...
   [ 117  118  119 ...  123  124  125]
   [ 126  127  128 ...  132  133  134]
   [ 135  136  137 ...  141  142  143]]

  [[ 144  145  146 ...  150  151  152]
   [ 153  154  155 ...  159  160  161]
   [ 162  163  164 ...  168  169  170]
   ...
   [ 189  190  191 ...  195  196  197]
   [ 198  199  200 ...  204  205  206]
   [ 207  208  209 ...  213  214  215]]

  [[ 216  217  218 ...  222  223  224]
   [ 225  226  227 ...  231  232  233]
   [ 234  235  236 ...  240  241  242]
   ...
   [ 261  262  263 ...  267  268  269]
   [ 270  271  272 ...  276  277  278]
   [ 279  280  281 ...  285  286  287]]

  [[ 288  289  290 ...  294 

In [65]:
## q20 How can we find the unique elements of an array?
###  use np.unique
a20=np.arange(8)
a20=a20.reshape((2,4))
a20=np.concatenate(a20,axis=0)
np.unique(a20)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
### q21 How can we find the intersection or difference of two arrays?
print(np.intersect1d(a20,a19))
print(np.setdiff1d(a20,a19) )## no output because all elements of a20 are also there in a19 
print(np.setdiff1d(a19,a20))

[0 1 2 3 4 5 6 7]
[]
[   8    9   10 ... 1437 1438 1439]


In [71]:
## q22 How can we find the boolean index of an array based on a certain condition?

a22=a20 > 5


print(a22)


[False False False False False False  True  True]


In [73]:
### q23 How can we apply mathematical functions to all elements of an array?
## A. most numpy mathematical functions do the operation element-wise for every element of the array that is given as its argument
## eg.
np.sin(a20)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ])